name: Github Actions Demo
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Nice to meet you TillPos'
        required: true
        default: 'Sinnv2710'
jobs:
  execute-running:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
            runTests: false
            build: yarn

      - name: running
        uses: cypress-io/github-action@v2
        with:
            start: yarn cypress run
